<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VesselSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('vessels')->delete();

        DB::table('vessels')->insert(array (
            0 =>
            array (
                'id' => 1,
                'serial_number' => 'V0001',
                'imo_number' => 'IMO 9674083',
                'name' => 'Kelud',
                'type' => 'Container',
                'status' => 'ACTIVE',
                'dwt' => 50,
                'gt' => 30,
                'voyage_route_from' => 'BLW - Belawan',
                'voyage_route_to' => 'TPR - Tanjung Priok',
                'vessel_speed' => 20,
                'berth' => 24,
                'draft' => 12,
                'length' => 250,
                'width' => 40,
                'main_eng_total' => 2,
                'main_eng_power' => 20000,
                'aux_eng_total' => 2,
                'aux_power' => 1000,
                'main_eng_fuel' => 'Heavy Fuel Oil(HFO)',
                'aux_eng_fuel' => 'Marine Gasoil(MGO)',
                'main_eng' => 120,
            ),
            1 =>
            array (
                'id' => 2,
                'serial_number' => 'V0002',
                'imo_number' => 'IMO 7632909',
                'name' => 'Samudera Bintang',
                'type' => 'Bulk Carrier',
                'status' => 'ON-HOLD',
                'dwt' => 120,
                'gt' => 70,
                'voyage_route_from' => 'MAK - Makassar',
                'voyage_route_to' => 'SUB - Tanjung Perak',
                'vessel_speed' => 15,
                'berth' => 48,
                'draft' => 15,
                'length' => 300,
                'width' => 50,
                'main_eng_total' => 3,
                'main_eng_power' => 30000,
                'aux_eng_total' => 3,
                'aux_power' => 1500,
                'main_eng_fuel' => 'Marine Diesel Oil (MDO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 100,
            ),
            2 =>
            array (
                'id' => 3,
                'serial_number' => 'V0003',
                'imo_number' => 'IMO 4067769',
                'name' => 'Angin Laut',
                'type' => 'Oil Tanker',
                'status' => 'UNACTIVE',
                'dwt' => 150,
                'gt' => 90,
                'voyage_route_from' => 'SRG - Tanjung Emas',
                'voyage_route_to' => 'SUB - Tanjung Perak',
                'vessel_speed' => 12,
                'berth' => 36,
                'draft' => 18,
                'length' => 350,
                'width' => 60,
                'main_eng_total' => 1,
                'main_eng_power' => 50000,
                'aux_eng_total' => 4,
                'aux_power' => 2000,
                'main_eng_fuel' => 'Low Sulphur Fuel Oil (LSFO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 75,
            ),
            3 =>
            array (
                'id' => 4,
                'serial_number' => 'V0004',
                'imo_number' => 'IMO 5900259',
                'name' => 'Evergreen Indonesia',
                'type' => 'General Cargo Ship',
                'status' => 'ACTIVE',
                'dwt' => 30,
                'gt' => 20,
                'voyage_route_from' => 'SUB - Tanjung Perak',
                'voyage_route_to' => 'SRG - Tanjung Emas',
                'vessel_speed' => 18,
                'berth' => 12,
                'draft' => 8,
                'length' => 180,
                'width' => 30,
                'main_eng_total' => 1,
                'main_eng_power' => 15000,
                'aux_eng_total' => 2,
                'aux_power' => 800,
                'main_eng_fuel' => 'Marine Diesel Oil (MDO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 150,
            ),
            4 =>
            array (
                'id' => 5,
                'serial_number' => 'V0005',
                'imo_number' => 'IMO 3490742',
                'name' => 'Jelajah Nusantara',
                'type' => 'Ro-Ro Vessel',
                'status' => 'ACTIVE',
                'dwt' => 20,
                'gt' => 15,
                'voyage_route_from' => 'TPR - Tanjung Priok',
                'voyage_route_to' => 'MAK - Makassar',
                'vessel_speed' => 22,
                'berth' => 18,
                'draft' => 6,
                'length' => 150,
                'width' => 25,
                'main_eng_total' => 2,
                'main_eng_power' => 10000,
                'aux_eng_total' => 1,
                'aux_power' => 500,
                'main_eng_fuel' => 'Heavy Fuel Oil (HFO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 180,
            ),
            5 =>
            array (
                'id' => 6,
                'serial_number' => 'V0006',
                'imo_number' => 'IMO 4274211',
                'name' => 'Cakrawala',
                'type' => 'Cruise Ship',
                'status' => 'ON-HOLD',
                'dwt' => 80,
                'gt' => 50,
                'voyage_route_from' => 'BLW - Belawan',
                'voyage_route_to' => 'MAK - Makassar',
                'vessel_speed' => 25,
                'berth' => 30,
                'draft' => 10,
                'length' => 220,
                'width' => 35,
                'main_eng_total' => 4,
                'main_eng_power' => 40000,
                'aux_eng_total' => 3,
                'aux_power' => 1200,
                'main_eng_fuel' => 'Low Sulphur Fuel Oil (LSFO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 130,
            ),
            6 =>
            array (
                'id' => 7,
                'serial_number' => 'V0007',
                'imo_number' => 'IMO 8353235',
                'name' => 'Penjelajah',
                'type' => 'Ferry',
                'status' => 'ACTIVE',
                'dwt' => 40,
                'gt' => 25,
                'voyage_route_from' => 'MAK - Makassar',
                'voyage_route_to' => 'BLW - Belawan',
                'vessel_speed' => 19,
                'berth' => 20,
                'draft' => 7,
                'length' => 190,
                'width' => 30,
                'main_eng_total' => 2,
                'main_eng_power' => 25000,
                'aux_eng_total' => 2,
                'aux_power' => 1000,
                'main_eng_fuel' => 'Marine Diesel Oil (MDO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 140,
            ),
            7 =>
            array (
                'id' => 8,
                'serial_number' => 'V0008',
                'imo_number' => 'IMO 9295418',
                'name' => 'Horizon',
                'type' => 'Tugboat',
                'status' => 'UNACTIVE',
                'dwt' => 10,
                'gt' => 5,
                'voyage_route_from' => 'SRG - Tanjung Emas',
                'voyage_route_to' => 'BLW - Belawan',
                'vessel_speed' => 12,
                'berth' => 10,
                'draft' => 4,
                'length' => 120,
                'width' => 20,
                'main_eng_total' => 1,
                'main_eng_power' => 8000,
                'aux_eng_total' => 1,
                'aux_power' => 400,
                'main_eng_fuel' => 'Heavy Fuel Oil (HFO)',
                'aux_eng_fuel' => 'Marine Gasoil (MGO)',
                'main_eng' => 100,
            ),
        ));
    }
}
